author:
  name: 'CrazyTim'
  email: impdeveloper@gmail.com

titles_from_headings:
  enabled: false

lang: 'en_AU'

include: ['_pages']

theme: 'minima'

# Items are sorted (default) by date ASC
collections:
  articles:
    output: true
    permalink: /blog/:path/

timezone: 'Australia/Melbourne'

encoding: 'utf-8'
